### ISSUE TITLE
macOS setup

### ISSUE THREAD

**Issue by codecheffy** [koekeishiya/dotfiles#1]
how do i setup these dotfiles for macOS?

**Comment by asmvik** [comment]
Uh, nothing special. The repo just has the configuration file for whatever program, and you have to copy them to their expected location (with the required name).

E.g: `vim/vimrc` should be placed as  `$HOME/.vimrc`

Edit: You probably should not overwrite your own files without backups as there is no guarantee that my configuration files will work properly on your system.

The best approach would be to go through the files and see if you can identify parts that you does the things you care about, and then integrate these parts into your existing config.
