### ISSUE TITLE
Mind sharing your wallpaper?

### ISSUE THREAD

**Issue by hovsater** [koekeishiya/dotfiles#10]
Hi, I've been using setup for quite some time with a few adjustments to your colorscheme for various languages. If you don't mind, I'd love to get my hands on that awesome wallpaper of yours. 🙂

**Comment by asmvik** [comment]
![wallhaven-4806522](https://user-images.githubusercontent.com/6175959/76704563-2b163200-66da-11ea-8016-916ccb60e7bb.png)

This is a recolor I did of the original picture that was found on wallhaven. I don't know if the original version exists anymore - at least I did not manage to find it.

**Comment by hovsater** [comment]
Thanks, @koekeishiya! That will do just fine. 👍
