### ISSUE TITLE
Hyper

### ISSUE THREAD

**Issue by tjfwalker** [koekeishiya/dotfiles#3]
The screenshots show you using Hyper, customized. Though, I don't see your .hyper.js or related. Also, I noticed some nifty looking status lines at the bottom of your term windows but failed to find where in these dotfiles those are setup. Care to share, @koekeishiya ?

**Comment by asmvik** [comment]
The terminal is my own fork of *Kitty* and the statusline is from tmux

**Comment by tjfwalker** [comment]
Good stuff. Thanks.
