### ISSUE TITLE
Vim colors

### ISSUE THREAD

**Issue by jonathandion** [koekeishiya/dotfiles#5]
Nice dotfiles.

I'm trying to install koe.new.vim color scheme but my colors are really different.

I'm using Kitty and nvim too.

Any idea?

**Comment by asmvik** [comment]
Mostly copied from my reply in https://github.com/koekeishiya/chunkwm/issues/21

--

Uh, I can't really say why. My full neovim environment can be found here: https://github.com/koekeishiya/dotfiles/tree/master/nvim

The theme I made is solely for C/C++ code, so if you are editing other types of text, that may affect what it looks like (as I have not tested this).

The theme ONLY set colors for the console version. IF you are running vim through some sort of UI (e.g: macvim or similar), the theme does not set the colors that you see above in my pictures.

The nvim colorscheme uses colors defined in your terminal, so you would have to set the colors in kitty.conf as well. You probably already did this though.

**Comment by jonathandion** [comment]
Thanks, @koekeishiya I figured out! :+1:
