### ISSUE TITLE
more information about those lines 

### ISSUE THREAD

**Issue by Kwask94** [koekeishiya/dotfiles#6]
chunkc tiling::rule --owner mpv --state float &
chunkc tiling::rule --owner kitty --role AXWindow --subrole AXDialog --state tile &
chunkc tiling::rule --owner Finder --name Copy --state float &
chunkc tiling::rule --owner \"App Store\" --state float &
chunkc tiling::rule --owner Spotify --desktop 5 --follow-desktop &
chunkc tiling::rule --owner Steam --desktop 5 --follow-desktop &
chunkc tiling::rule --owner Discord --desktop 5 --follow-desktop &

thanks

**Comment by asmvik** [comment]
See https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#window-rules
