### ISSUE TITLE
What is the bar shown in your readme screenshot?

### ISSUE THREAD

**Issue by yngtodd** [koekeishiya/dotfiles#7]
Hey koekeishiya,

Thank you so much for the work that you have down on chunkwm. You are awesome. Just wanted to ask, what are the bars you have shown on the top and bottom of your README screenshot?

**Comment by asmvik** [comment]
The top and bottom bar is created by an Übersicht widget: https://github.com/koekeishiya/Statusbar
I don't really use it these days, bit it should still work fine.

**Comment by yngtodd** [comment]
Great, thank you!
