### ISSUE TITLE
How can you customize macos's menu bar and dock?

### ISSUE THREAD

**Issue by CavalloneChen** [koekeishiya/dotfiles#9]
Your screenshots are amazingly beautiful, I wonder which set of tools do you use to customize menu bar and dock? I had no idea mac's de can be so customizable.

**Comment by asmvik** [comment]
I have the macOS menubar and Dock set to autohide. The bar you see in the screenshot is created and updated by *yabai*, a tiling window manager I made for macOS.

**Comment by CavalloneChen** [comment]
I see, thanks!
